authorName: default
experimentName: uncertain_brats_unet
trialConcurrency: 2
maxExecDuration: 1h
maxTrialNum: 1000
trainingServicePlatform: local
searchSpacePath: search_space.json
useAnnotation: false
tuner:
    builtinTunerName: TPE

trial:
    command: zsh train_brats.sh
    codeDir: .
    gpuNum: 0 
