python train.py \
       --workers 4 \
       --lr 10 \
       --epochs 100 \
       --gpu-ids 0 \
       --batch-size 32 \
       --test-batch-size 1 \
       --checkname unet-lidc \
       --eval-interval 5 \
       --dataset lidc \
       --loss-type dice \
       --nchannels 1 \
       --model unet \
       --nclass 4 \
       --task-num 0
